title: home
baseurl: ""  # Karena ini repo user page (bukan project page), baseurl harus kosong
url: "anandaaputrinabilla.github.io"

sass:
  style: compressed
include:
  - assets


theme: null

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
