title: home
baseurl: "" 
url: "https://anandaaputrinabilla.github.io/"

sass: 
  sass_dir: _sass
  style: compressed
  sass_dir: _scss

theme: null

plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag